---
- name: Install Duplicity Repo
  apt_repository:
    repo: "ppa:duplicity-team/ppa"
  tags:
    - apt
    - backup
    - packages

- name: Purge paramiko package
  apt:
    name: "{{ packages }}"
    state: absent
    purge: yes
  vars:
    packages:      
    - python-paramiko
  tags:
    - apt
    - backup
    - packages

- name: Install base packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:      
    - python-pip
    - virtualenv
  tags:
    - apt
    - backup
    - packages

- name: Pip install 
  pip:
    name: "{{ packages }}"
  vars:
    packages:      
    - setuptools
    - paramiko
  tags:
    - pip
    - backup
    - packages

- name: Install base packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:      
    - duplicity
  tags:
    - apt
    - backup
    - packages
