---
- name: check if .ssh directory in /root/ exists
  file:
    path: /root/.ssh
    state: directory
    mode: 0700
  tags:
    - backup
    - ssh

- name: copy ssh private key for Backuplocation
  copy:
    content: "{{ ssh_private_key_vault }}"
    dest: /root/.ssh/id_rsa
    mode: 0600
  tags:
    - backup
    - ssh

- name: Remove Backuplocation to known_hosts
  known_hosts:
    name: "{{ item.name }}"
    key: "{{ item.key }}"
    state: absent
  with_items:
    - name: backup.pcopfer.de
      key: "{{ lookup('file', 'backup.pcopfer.de.pub') }}"
  tags:
    - backup
    - ssh

- name: Add Backuplocation to known_hosts
  known_hosts:
    name: "{{ item.name }}"
    key: "{{ item.key }}"
  with_items:
    - name: u152030.your-backup.de
      key: "{{ lookup('file', 'u152030.your-backup.de') }}"
    - name: backup.pcopfer.de
      key: "{{ lookup('file', 'backup.pcopfer.de_neu.pub') }}"
  tags:
    - backup
    - ssh
