---
- name: check if .ssh directory in /root/ exists
  file:
    path: /root/.ssh
    state: directory
    mode: 0700
  tags:
    - backup
    - ssh

- name: copy ssh private key for Backuplocations
  copy:
    content: "{{ duplicity_priv_ssh_key }}"
    dest: /root/.ssh/id_rsa
    mode: 0600
  tags:
    - backup
    - ssh

- name: Add public host keys of Backuplocations to known_hosts
  known_hosts:
    name: "{{ duplicity_target_domain }}"
    key: "{{ duplicity_target_pub_host_key }}"
  tags:
    - backup
    - ssh
